// <auto-generated />
using System;
using GameAnalytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameAnalytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameAnalytics.Models.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("GameAnalytics.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EventModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "EventTimestamp");

                    b.HasIndex("ProjectId", "EventModelId", "EventTimestamp");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GameAnalytics.Models.EventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EventModels");
                });

            modelBuilder.Entity("GameAnalytics.Models.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EventModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GameAnalytics.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("SystemUserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GameAnalytics.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuilderJson")
                        .HasColumnType("text");

                    b.Property<int>("ChartType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SqlRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("GameAnalytics.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("DurationSeconds")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventsCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "StartTime");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GameAnalytics.Models.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("GameAnalytics.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalRevenue")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "FirstSeen");

                    b.HasIndex("ProjectId", "LastSeen");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameAnalytics.Models.Dashboard", b =>
                {
                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Dashboards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GameAnalytics.Models.Event", b =>
                {
                    b.HasOne("GameAnalytics.Models.EventModel", "EventModel")
                        .WithMany("Events")
                        .HasForeignKey("EventModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAnalytics.Models.Session", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameAnalytics.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventModel");

                    b.Navigation("Project");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameAnalytics.Models.EventModel", b =>
                {
                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("EventModels")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GameAnalytics.Models.Parameter", b =>
                {
                    b.HasOne("GameAnalytics.Models.EventModel", "EventModel")
                        .WithMany("Parameters")
                        .HasForeignKey("EventModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Parameters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventModel");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GameAnalytics.Models.Project", b =>
                {
                    b.HasOne("GameAnalytics.Models.SystemUser", "SystemUser")
                        .WithMany("Projects")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("GameAnalytics.Models.Report", b =>
                {
                    b.HasOne("GameAnalytics.Models.Dashboard", "Dashboard")
                        .WithMany("Reports")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GameAnalytics.Models.Session", b =>
                {
                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Sessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAnalytics.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameAnalytics.Models.User", b =>
                {
                    b.HasOne("GameAnalytics.Models.Project", "Project")
                        .WithMany("Users")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GameAnalytics.Models.Dashboard", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("GameAnalytics.Models.EventModel", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("GameAnalytics.Models.Project", b =>
                {
                    b.Navigation("Dashboards");

                    b.Navigation("EventModels");

                    b.Navigation("Events");

                    b.Navigation("Parameters");

                    b.Navigation("Reports");

                    b.Navigation("Sessions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GameAnalytics.Models.Session", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GameAnalytics.Models.SystemUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GameAnalytics.Models.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
